library(reshape2) #for melt - note that many reshape2 functions are now available using tidyr, so probably best to use just tidyr
library(tidyr)
library(dplyr) #note that many functions are similar for plyr and dplyr but have slightly different syntax in dplyr. Use the newer one (dplyr) to avoid issues between two packages. 
library(ggplot2)
library(lubridate) 
fwdata<-read.csv("FW_master_2016_foranalysis.csv", header=T, as.is=T)
levels(as.factor(fwdata$island))
fwdata$island <- gsub("guam ", "guam",fwdata$island)
fwdata$island <- gsub("Rota", "rota",fwdata$island)
fwdata$island <- gsub("Saipan", "saipan",fwdata$island)
levels(as.factor(fwdata$wilt))
fwdata$wilt <- gsub("", "no",fwdata$wilt)
fwdata$wilt <- gsub("noynoenosno", "yes",fwdata$wilt)
fwdata$wilt <- gsub("nonnoano", "na",fwdata$wilt)
fwdata$wilt <- gsub("nonnoono", "no",fwdata$wilt)
fwdata$wilt <- gsub("noNnoono", "no",fwdata$wilt)
fwdata$wilt <- gsub("noNnoOno", "no",fwdata$wilt)
fwdata$wilt <- gsub("noNnoono no", "no",fwdata$wilt)
fwdata$wilt <- gsub("no no", "no",fwdata$wilt)